name: Revert Specified Commits

on:
  workflow_dispatch:

jobs:
  revert_commits:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: blu_spark_ksu_next_susfs-13
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Show recent commits for debugging
      run: git log --oneline --decorate --graph -30

    - name: Revert commit 1
      run: git revert 14a995bf072afaef17dbcb942761e2e6d051605c --no-edit 
    - name: Revert commit 2
      run: git revert df212b0567dc63ab1ae94e3bbf98b53c1002c54f --no-edit 
    - name: Revert commit 3
      run: git revert 687ff16f24a0abe7c7a7a9e06a75c0231b5a6aa8 --no-edit 
    - name: Revert commit 4
      run: git revert ada1b7a8b16654d5c625d84a98ed83d68ee600b2 --no-edit
    - name: Revert commit 5
      run: git revert bc253ab3f05a47d4eb3acc97c27204e7c2c9f827 --no-edit 
    - name: Revert commit 6
      run: git revert d581803cce26a72b885fcbba915326d2c0d613a1 --no-edit 
    - name: Show git status
      run: git status

    - name: Push changes
      run: git push origin HEAD:blu_spark_ksu_next_susfs-13
